version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app/uploads:/app/uploads
      - ./app/storage:/app/storage
    environment:
      - FLASK_APP=api.py
      - FLASK_ENV=development